import Head from 'next/head'
import Header from '../components/header'
import comida from '../img/comida.png'
import Image from 'next/image'

export default function Home() {
  function Titulo({children}){
    return <span className='font-extrabold text-4xl font-sans block py-1 md:text-8xl'> 
      {children}
    </span>
  }
  function Textopequeño({children}){
    return <div className='py-6 font-sans text-black font-medium md:text-3xl'>
      {children}
      </div>
  }
  function Imagendeesta(){
    return <div className='m-6 '>
      <Image  
    className='hover:scale-110 transition'
    src={comida}
    alt='comida'
    ></Image>
    </div>
    
  }
  return (
    <div>
      <Head>
        <title>Grandota Restaurante</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className=' py-16 flex flex-col justify-between px-4'>
        
        <Textopequeño>Somos un espacio donde tenemos</Textopequeño>
        <Titulo>Servicio excelente</Titulo>
        <Titulo>Ambiente acogedor</Titulo>
        <Titulo> Experiencia única</Titulo>
        <Textopequeño>Atencion presencial y por Delivery</Textopequeño>
        <div className=' flex justify-center py-4'>
          <button className='text-white bg-blue-700 py-3 px-4 inline-block rounded-full uppercase'>ver carta +</button>
        </div>
      </main>
      <div className='grid grid-cols-1 md:grid-cols-2'>
        <Imagendeesta/>
        <Imagendeesta/>
        <Imagendeesta/>
        <Imagendeesta/>

      </div>
    </div>
  )
}
